### ISSUE TITLE
Roadmap: ArmorStandEditor

### ISSUE THREAD

**Issue by Wolfieheart** [Wolfst0rm/ArmorStandEditor-Issues#11]
Priority for NEXT:
- [ ] Implementation of #9 and #10
- [ ] Introduction of #23 -> Soft Depend, Depends if Plugin is there or not :) (See Towny Implementation for more info)
- [x] Reintroduction of #24 -> Also SoftDepends
- [ ] Introduction of a few extra functions

**Comment by Wolfieheart** [comment]
1.17.1-30 Release Notes:

Contains the introduction for Disabling Equipment Slots. 

I wanted to also fix #3 at some stage, but at the moment I can not get it into a place where both myself and the reporter would be happy with it, without fully preventing Flint/EditTool from being put into the frame due to the fact that Minecraft likes firing in the event that you interact with an itemFrame twice:
- first put the item in 
- then make it invis. 

Sorry if you were expecting that to be fixed in this release, but it is an issue I think that will not be fixed unless there is a separate event for Items going into things.

**Comment by Wolfieheart** [comment]
1.18-pre5-31 Release Notes and Warnings:

- Currently supports 1.18-pre5-30, perfectly fine.
- Added new Language Support file for German (thank you Sulort)

Comes with the same disclaimer as that for Spigot 1.18-pre5:
> Remember that this is a pre-release version. Significant changes may occur before release and upgrades to other pre-releases should not be expected.

> Please note that we do not consider pre-releases a stable version. In particular there will be no attempt at compatibility between 1.18-pre5 and 1.18. That is to say the existence of 1.18-pre5 will be ignored when 1.18 releases. You have been warned.
